### ISSUE TITLE
warning [M0195], this function call implicitly requires `system` capability - solution

### ISSUE THREAD

**Issue by testpuddle** [motoko-bootcamp/reboot#1]
User-defined functions must now declare an explicit system pseudo-type parameter if they require system capabilities. 

I went and read the info about the warning after our unconference call and so I am passing this along.

Line 19: 

let daily = Timer.recurringTimer(#nanoseconds(nanosecondsPerDay), _kill);

to

let daily = Timer.recurringTimer<system>(#nanoseconds(nanosecondsPerDay), _kill);

**Comment by seb-icp** [comment]
What is the difference? I'm guessing you forgot some syntax here

**Comment by testpuddle** [comment]
Strange... when I edit it it has the correct entry that I put.
let daily = Timer.recurringTimer<system>(#nanoseconds(nanosecondsPerDay), _kill);

**Comment by seb-icp** [comment]
Great, thank you Ted. I've just made a PR to include that.
