### ISSUE TITLE
The subnet in the README is restricted from being freely deployed to

### ISSUE THREAD

**Issue by ByronBecker** [motoko-bootcamp/reboot#2]
We can't deploy to `jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe` because it isn't openly allowed yet.

https://forum.dfinity.org/t/canister-not-deployable-on-specific-subnet/30470

https://dashboard.internetcomputer.org/proposal/126769

**Comment by seb-icp** [comment]
We are migrating to another subnet: bkfrj-6k62g-dycql-7h53p-atvkj-zg4to-gaogh-netha-ptybj-ntsgw-rqe

This one is open to anyone and is really easy to locate since it's the European subnet.
