### ISSUE TITLE
unused identifier daily

### ISSUE THREAD

**Issue by samlinux** [motoko-bootcamp/reboot#3]
I know there is no claim to perfection but the following could easily be avoided.

/Users/rbole/Sites/ois/reboot/src/user/main.mo:30.9-30.14: warning [M0194], unused identifier daily (delete or rename to wildcard `_` or `_daily`)

from
 let daily = Timer.recurringTimer<system>(#nanoseconds(nanosecondsPerDay), _kill);

to

 let _ = Timer.recurringTimer<system>(#nanoseconds(nanosecondsPerDay), _kill);

**Comment by seb-icp** [comment]
Thanks Roland, I moved the user-canister repository but I took into account your recommendation.

**Comment by seb-icp** [comment]
https://github.com/motoko-bootcamp/you
